/** Token spans for AI SDK demo — joined string must match CODE_DEMO in mac-os-terminal.tsx */

export type MotShClass =
  | "mot-sh-kw"
  | "mot-sh-str"
  | "mot-sh-fn"
  | "mot-sh-num"
  | "mot-sh-prop"
  | "mot-sh-var"
  | "mot-sh-punct"

export const CODE_SYNTAX_PARTS: ReadonlyArray<{ t: string; c: MotShClass }> = [
  { t: "import ", c: "mot-sh-kw" },
  { t: "{ ", c: "mot-sh-punct" },
  { t: "generateText", c: "mot-sh-fn" },
  { t: ", ", c: "mot-sh-punct" },
  { t: "tool", c: "mot-sh-fn" },
  { t: " } ", c: "mot-sh-punct" },
  { t: "from ", c: "mot-sh-kw" },
  { t: "'ai'", c: "mot-sh-str" },
  { t: ";\n", c: "mot-sh-punct" },
  { t: "import ", c: "mot-sh-kw" },
  { t: "{ ", c: "mot-sh-punct" },
  { t: "z", c: "mot-sh-fn" },
  { t: " } ", c: "mot-sh-punct" },
  { t: "from ", c: "mot-sh-kw" },
  { t: "'zod'", c: "mot-sh-str" },
  { t: ";\n\n", c: "mot-sh-punct" },
  { t: "const", c: "mot-sh-kw" },
  { t: " { ", c: "mot-sh-punct" },
  { t: "text", c: "mot-sh-var" },
  { t: " } ", c: "mot-sh-punct" },
  { t: "= ", c: "mot-sh-punct" },
  { t: "await", c: "mot-sh-kw" },
  { t: " ", c: "mot-sh-punct" },
  { t: "generateText", c: "mot-sh-fn" },
  { t: "({\n  ", c: "mot-sh-punct" },
  { t: "model", c: "mot-sh-prop" },
  { t: ": ", c: "mot-sh-punct" },
  { t: "'openai/gpt-5.2'", c: "mot-sh-str" },
  { t: ",\n  ", c: "mot-sh-punct" },
  { t: "prompt", c: "mot-sh-prop" },
  { t: ": ", c: "mot-sh-punct" },
  { t: "'What is the weather like today in San Francisco?'", c: "mot-sh-str" },
  { t: ",\n  ", c: "mot-sh-punct" },
  { t: "tools", c: "mot-sh-prop" },
  { t: ": {\n    ", c: "mot-sh-punct" },
  { t: "getWeather", c: "mot-sh-prop" },
  { t: ": ", c: "mot-sh-punct" },
  { t: "tool", c: "mot-sh-fn" },
  { t: "({\n      ", c: "mot-sh-punct" },
  { t: "description", c: "mot-sh-prop" },
  { t: ": ", c: "mot-sh-punct" },
  { t: "'Get the weather in a location'", c: "mot-sh-str" },
  { t: ",\n      ", c: "mot-sh-punct" },
  { t: "inputSchema", c: "mot-sh-prop" },
  { t: ": ", c: "mot-sh-punct" },
  { t: "z", c: "mot-sh-fn" },
  { t: ".", c: "mot-sh-punct" },
  { t: "object", c: "mot-sh-fn" },
  { t: "({\n        ", c: "mot-sh-punct" },
  { t: "location", c: "mot-sh-prop" },
  { t: ": ", c: "mot-sh-punct" },
  { t: "z", c: "mot-sh-fn" },
  { t: ".", c: "mot-sh-punct" },
  { t: "string", c: "mot-sh-fn" },
  { t: "()", c: "mot-sh-punct" },
  { t: ".", c: "mot-sh-punct" },
  { t: "describe", c: "mot-sh-fn" },
  { t: "(", c: "mot-sh-punct" },
  { t: "'The location to get the weather for'", c: "mot-sh-str" },
  { t: ")", c: "mot-sh-punct" },
  { t: ",\n      }),\n      ", c: "mot-sh-punct" },
  { t: "execute", c: "mot-sh-prop" },
  { t: ": ", c: "mot-sh-punct" },
  { t: "async", c: "mot-sh-kw" },
  { t: " ", c: "mot-sh-punct" },
  { t: "({ ", c: "mot-sh-punct" },
  { t: "location", c: "mot-sh-var" },
  { t: " }) => ({\n        ", c: "mot-sh-punct" },
  { t: "location", c: "mot-sh-prop" },
  { t: ",\n        ", c: "mot-sh-punct" },
  { t: "temperature", c: "mot-sh-prop" },
  { t: ": ", c: "mot-sh-punct" },
  { t: "72", c: "mot-sh-num" },
  { t: " + ", c: "mot-sh-punct" },
  { t: "Math", c: "mot-sh-fn" },
  { t: ".", c: "mot-sh-punct" },
  { t: "floor", c: "mot-sh-fn" },
  { t: "(", c: "mot-sh-punct" },
  { t: "Math", c: "mot-sh-fn" },
  { t: ".", c: "mot-sh-punct" },
  { t: "random", c: "mot-sh-fn" },
  { t: "() * ", c: "mot-sh-punct" },
  { t: "21", c: "mot-sh-num" },
  { t: ") - ", c: "mot-sh-punct" },
  { t: "10", c: "mot-sh-num" },
  { t: ",\n      }),\n    }),\n  },\n});", c: "mot-sh-punct" },
]

export const CODE_DEMO = CODE_SYNTAX_PARTS.map((p) => p.t).join("")
